# Generated by Django 5.2.11 on 2026-02-18 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sap_id', models.CharField(max_length=20, unique=True)),
                ('roll_number', models.CharField(max_length=20)),
                ('student_class', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('program', models.CharField(choices=[('BTECH_CS', 'BTech CS'), ('BTECH_CS_DS', 'BTech CS-DS'), ('BTECH_CE', 'BTech CE'), ('BTECH_IT', 'BTech IT'), ('BTECH_AIML', 'BTech AIML'), ('MBA_TECH_CE', 'MBATech CE')], max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='studentgroup.teacher')),
            ],
        ),
    ]
